import type { BusinessProfile } from '../../types/src/index.ts';

export const MOCK_GBP_BUSINESS: BusinessProfile = {
  id: 'biz-abc-dental',
  name: 'ABC Dental Clinic',
  placeId: 'ChIJN1t_tDeuEmsRUsoyG83frY4',
  address: 'No 45 Galle Road, Colombo 03, Sri Lanka',
  street: 'No 45 Galle Road',
  city: 'Colombo',
  state: 'Western Province',
  postalCode: '00300',
  country: 'LK',
  phone: '+94 11 234 5678',
  website: 'https://abcdentalcolombo.example.com',
  primaryCategory: 'Dentist',
  secondaryCategories: [
    'Cosmetic Dentist',
    'Dental Clinic',
    'Teeth Whitening Service',
    'Orthodontist',
  ],
  rating: 4.7,
  reviewCount: 247,
  openingHours: 'Mon-Fri: 08:00 - 18:00, Sat: 09:00 - 14:00, Sun: Closed',
  regularHours: {
    monday: { open: '08:00', close: '18:00' },
    tuesday: { open: '08:00', close: '18:00' },
    wednesday: { open: '08:00', close: '18:00' },
    thursday: { open: '08:00', close: '18:00' },
    friday: { open: '08:00', close: '18:00' },
    saturday: { open: '09:00', close: '14:00' },
    sunday: { open: '', close: '', closed: true },
  },
  specialHours: ['2026-12-25: Closed', '2026-01-01: 10:00 - 14:00'],
  description:
    'ABC Dental Clinic is Colombo’s premier multi-specialty dental practice offering advanced cosmetic dentistry, orthodontic aligners, dental implants, pain-free root canals, and comprehensive oral hygiene care for children and adults.',
  services: [
    'Dental Cleaning & Scaling',
    'Teeth Whitening',
    'Dental Implants',
    'Root Canal Therapy',
    'Invisible Orthodontic Aligners',
    'Composite Fillings',
    'Porcelain Veneers',
    'Emergency Tooth Extractions',
  ],
  products: [
    'Custom Night Guards',
    'Professional At-Home Whitening Kits',
    'Therapeutic Fluoride Enamel Gel',
  ],
  attributes: {
    has_wheelchair_accessible_entrance: true,
    has_wheelchair_accessible_parking: true,
    requires_appointment: true,
    identifies_as_women_owned: false,
    credit_cards_accepted: true,
  },
  photosCount: 28,
  hasCoverPhoto: true,
  hasLogo: true,
  postsCount: 6,
  lastPostDate: '2026-08-28',
  latitude: 6.9015,
  longitude: 79.8529,
  mapsUrl: 'https://maps.google.com/?cid=123456789012345',
  dataSource: 'Google Business Profile API',
};

export const MOCK_BUSINESS_LIST: BusinessProfile[] = [
  MOCK_GBP_BUSINESS,
  {
    id: 'biz-colombo-auto',
    name: 'Colombo Auto Care Specialists',
    placeId: 'ChIJX_demo_autocare',
    address: '112 Baseline Road, Colombo 09, Sri Lanka',
    street: '112 Baseline Road',
    city: 'Colombo',
    state: 'Western Province',
    postalCode: '00900',
    country: 'LK',
    phone: '+94 11 288 9911',
    website: 'https://colomboautocare.example.com',
    primaryCategory: 'Car Repair and Maintenance Service',
    secondaryCategories: ['Auto Electrical Service', 'Brake Shop', 'Tire Shop'],
    rating: 4.9,
    reviewCount: 182,
    openingHours: 'Mon-Sat: 07:30 - 19:00, Sun: Closed',
    regularHours: {
      monday: { open: '07:30', close: '19:00' },
      tuesday: { open: '07:30', close: '19:00' },
      wednesday: { open: '07:30', close: '19:00' },
      thursday: { open: '07:30', close: '19:00' },
      friday: { open: '07:30', close: '19:00' },
      saturday: { open: '07:30', close: '17:00' },
      sunday: { open: '', close: '', closed: true },
    },
    description: 'Expert automotive diagnostic, hybrid battery reconditioning, mechanical repairs, and lube services.',
    services: ['Hybrid Battery Service', 'Computer Engine Diagnostics', 'Periodic Maintenance Service', 'Wheel Alignment'],
    photosCount: 45,
    hasCoverPhoto: true,
    hasLogo: true,
    postsCount: 14,
    lastPostDate: '2026-09-02',
    latitude: 6.9312,
    longitude: 79.8778,
    mapsUrl: 'https://maps.google.com/?cid=987654321098765',
    dataSource: 'Google Maps public information',
  },
  {
    id: 'biz-xyz-restaurant',
    name: 'The Cinnamon Kitchen Colombo',
    placeId: 'ChIJY_demo_restaurant',
    address: '28 Alfred House Gardens, Colombo 03, Sri Lanka',
    street: '28 Alfred House Gardens',
    city: 'Colombo',
    state: 'Western Province',
    postalCode: '00300',
    country: 'LK',
    phone: '+94 11 250 1122',
    website: 'https://cinnamonkitchen.example.com',
    primaryCategory: 'Restaurant',
    secondaryCategories: ['Sri Lankan Restaurant', 'Seafood Restaurant'],
    rating: 4.3,
    reviewCount: 95,
    openingHours: 'Tue-Sun: 12:00 - 23:00, Mon: Closed',
    description: 'Authentic Ceylon spices, fresh seafood curries, and tropical courtyard dining.',
    services: ['Dine-in', 'Private Event Catering', 'Takeaway'],
    photosCount: 62,
    hasCoverPhoto: true,
    hasLogo: false,
    postsCount: 2,
    lastPostDate: '2026-07-15',
    latitude: 6.8965,
    longitude: 79.8553,
    mapsUrl: 'https://maps.google.com/?cid=554433221100998',
    dataSource: 'Google Maps public information',
  },
];
