import type { CompetitorComparisonItem } from '../../types/src/index.ts';

export const MOCK_COMPETITORS: CompetitorComparisonItem[] = [
  {
    id: 'comp-1',
    name: 'Colombo Smiles Dental Care',
    primaryCategory: 'Dentist',
    secondaryCategories: ['Cosmetic Dentist', 'Dental Implants Periodontist'],
    rating: 4.8,
    reviewCount: 381,
    website: 'https://colombosmiles.example.com',
    servicesCount: 21,
    photosCount: 64,
    profileCompletenessScore: 95,
    reviewResponseRate: 94,
    observedDifferences: [
      'Competitor has 134 more published reviews than your profile (381 vs 247).',
      'Lists 21 structured services in GBP compared to 12 services on your listing.',
      'Maintains a slightly higher review response rate of 94% vs 91%.',
      'Has 64 uploaded photos across clinical facilities and before/after cases.',
    ],
  },
  {
    id: 'comp-2',
    name: 'Royal Dental Care Colombo',
    primaryCategory: 'Dentist',
    secondaryCategories: ['Orthodontist', 'Emergency Dental Service'],
    rating: 4.5,
    reviewCount: 196,
    website: 'https://royaldental.example.com',
    servicesCount: 9,
    photosCount: 19,
    profileCompletenessScore: 80,
    reviewResponseRate: 72,
    observedDifferences: [
      'Your profile has 51 more reviews and a higher average rating (4.7 vs 4.5).',
      'Competitor lists 9 services compared to your 12 configured services.',
      'Competitor has a lower review response rate of 72% with multiple unanswered negative reviews.',
      'Specializes secondary category in Emergency Dental Service and Orthodontics.',
    ],
  },
  {
    id: 'comp-3',
    name: 'Premier Dental Specialists',
    primaryCategory: 'Dental Clinic',
    secondaryCategories: ['Dentist', 'Teeth Whitening Service', 'Pediatric Dentist'],
    rating: 4.6,
    reviewCount: 220,
    website: 'https://premierdental.example.com',
    servicesCount: 15,
    photosCount: 34,
    profileCompletenessScore: 88,
    reviewResponseRate: 85,
    observedDifferences: [
      'Lists Pediatric Dentist as an additional secondary category.',
      'Review volume is comparable (220 reviews vs 247).',
      'Publishes Google Posts on a regular bi-weekly schedule.',
    ],
  },
];
